### ISSUE TITLE
Failed randomly in SearchWithTagsAsync

### ISSUE THREAD

**Issue by Seng-Jik** [Xwilarg/NHentaiSharp#3]
When I searching with "loli" tag or "touhou" tag, it will failed randomly with exception `Your search didn't return any result, that probably mean one of the argument you provided is invalid`.

* Tag "loli"
    - Page 1 OK
    - Page 2 Failed
    - Page 3 Failed
    - Page 4 OK
    - Page 5 OK
* Tag "touhou"
    - Page 1 Failed
    - Page 2 OK
    - Page 3 OK
    - Page 4 OK
    - Page 5 OK

2021/11/25 12:28 (UTC)

Logs:

```
> SearchClient.SearchWithTagsAsync([|"loli"|], 1).Result;;
val it: NHentaiSharp.Search.SearchResult =
  NHentaiSharp.Search.SearchResult
    {elements = [|NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement|];
     numPages = 3245;
     numPerPage = 25;}

> SearchClient.SearchWithTagsAsync([|"loli"|], 2).Result;;
System.AggregateException: One or more errors occurred. (Your search didn't return any result, that probably mean one of the argument you provided is invalid)
 ---> NHentaiSharp.Exception.InvalidArgumentException: Your search didn't return any result, that probably mean one of the argument you provided is invalid
   at NHentaiSharp.Search.SearchResult..ctor(Object json)
   at NHentaiSharp.Core.SearchClient.SearchWithTagsAsync(String[] tags, Int32 page, PopularitySort sortOption)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at <StartupCode$FSI_0034>.$FSI_0034.main@()
已因出错而停止
> SearchClient.SearchWithTagsAsync([|"loli"|], 3).Result;;
System.AggregateException: One or more errors occurred. (Your search didn't return any result, that probably mean one of the argument you provided is invalid)
 ---> NHentaiSharp.Exception.InvalidArgumentException: Your search didn't return any result, that probably mean one of the argument you provided is invalid
   at NHentaiSharp.Search.SearchResult..ctor(Object json)
   at NHentaiSharp.Core.SearchClient.SearchWithTagsAsync(String[] tags, Int32 page, PopularitySort sortOption)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at <StartupCode$FSI_0035>.$FSI_0035.main@()
已因出错而停止
> SearchClient.SearchWithTagsAsync([|"loli"|], 4).Result;;
val it: NHentaiSharp.Search.SearchResult =
  NHentaiSharp.Search.SearchResult
    {elements = [|NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement;
                  NHentaiSharp.Search.GalleryElement|];
     numPages = 3245;
     numPerPage = 25;}
```

**Comment by Xwilarg** [comment]
Thanks for your bug report, sadly this is an issue on NHentai side

Example with "touhou" tag:

Page 1: https://nhentai.net/api/galleries/search?query=touhou&page=1
--> Error

Page 2: https://nhentai.net/api/galleries/search?query=touhou&page=2
--> No error

**Comment by Seng-Jik** [comment]
Thanks
